### ISSUE TITLE
AppCleaner

### ISSUE THREAD

**Issue by Rhyxidion** [elrumo/macOS_Big_Sur_icons_replacements#240] opened 2020-08-11 15:34 UTC
AppCleaner

https://freemacsoft.net/appcleaner/

**Comment by gottabeleGIT** [comment] 2020-08-11 17:46
Duplicate of #130

**Comment by gottabeleGIT** [comment] 2020-08-14 23:10
#268

**Comment by elrumo** [comment] 2020-08-15 11:26
Done

**Closed by elrumo** 2020-08-15 11:26 UTC
Labels: good first issue, new-icon-request
