### ISSUE TITLE
Latter search result was replaced by previous search result

### ISSUE THREAD

**Issue by kuige** [elrumo/macOS_Big_Sur_icons_replacements#1121] opened 2021-03-21 02:02 UTC
When I start typing, it instantly fetch the search result. However, sometimes the search result of my last typing is not correct, maybe it's replaced by the previous search result due to the async fetching ？

I think it's lacking some kind of sequential handling mechanism to ensure that the last showed result is the last search result.

For example:
<img width="1348" alt="image" src="https://user-images.githubusercontent.com/8212800/111891136-694fdb00-8a2b-11eb-876a-116acd230f1f.png">

After adding one space and removing the space at the end of typing to trigger another searching, the result is correct now:
<img width="1366" alt="image" src="https://user-images.githubusercontent.com/8212800/111891168-bc299280-8a2b-11eb-926c-2f8131b271e2.png">

**Comment by elrumo** [comment] 2021-03-26 00:56
You're right, I've spotted that issue too. I'll try to figure out a way to fix it.

**Comment by elrumo** [comment] 2021-07-02 20:13
I can't reproduce the issue anymore, I've made some changes to how the data is handled on the website so that might have fixed it. I'm closing the issue, but feel free to open it again if you encounter the bug.

**Closed by elrumo** 2021-07-02 20:13 UTC
Labels: website
